[2021-11-21 22:00:17,105] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: DWBI_HW2_dag.load manual__2021-11-21T21:00:03.772413+00:00 [queued]>
[2021-11-21 22:00:17,112] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: DWBI_HW2_dag.load manual__2021-11-21T21:00:03.772413+00:00 [queued]>
[2021-11-21 22:00:17,112] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 22:00:17,112] {taskinstance.py:1242} INFO - Starting attempt 1 of 6
[2021-11-21 22:00:17,112] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 22:00:17,123] {taskinstance.py:1262} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2021-11-21 21:00:03.772413+00:00
[2021-11-21 22:00:17,127] {standard_task_runner.py:52} INFO - Started process 43640 to run task
[2021-11-21 22:00:17,130] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'DWBI_HW2_dag', 'load', 'manual__2021-11-21T21:00:03.772413+00:00', '--job-id', '167', '--raw', '--subdir', '/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py', '--cfg-path', '/tmp/tmpyd5mk22o', '--error-file', '/tmp/tmp4zweog1s']
[2021-11-21 22:00:17,131] {standard_task_runner.py:77} INFO - Job 167: Subtask load
[2021-11-21 22:00:17,156] {logging_mixin.py:109} INFO - Running <TaskInstance: DWBI_HW2_dag.load manual__2021-11-21T21:00:03.772413+00:00 [running]> on host dj-XPS
[2021-11-21 22:00:17,185] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dj
AIRFLOW_CTX_DAG_ID=DWBI_HW2_dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2021-11-21T21:00:03.772413+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-21T21:00:03.772413+00:00
[2021-11-21 22:00:17,192] {logging_mixin.py:109} INFO - Successfully fetched the data
[2021-11-21 22:00:17,201] {logging_mixin.py:109} INFO -    Unnamed: 0  Gasoline  Make   origin
0           0         9     9  Germany
[2021-11-21 22:00:17,201] {logging_mixin.py:109} INFO - Successfully made contact with the database.
[2021-11-21 22:00:17,202] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py", line 130, in load
    cursor.execute("INSERT INTO CountryStats (Country,CarCount,GasolineCount) values(?,?,?)", row.origin, row.Make, row.Gasoline)
TypeError: function takes at most 2 arguments (4 given)
[2021-11-21 22:00:17,296] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=DWBI_HW2_dag, task_id=load, execution_date=20211121T210003, start_date=20211121T210017, end_date=20211121T210017
[2021-11-21 22:00:17,308] {standard_task_runner.py:88} ERROR - Failed to execute job 167 for task load
Traceback (most recent call last):
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py", line 130, in load
    cursor.execute("INSERT INTO CountryStats (Country,CarCount,GasolineCount) values(?,?,?)", row.origin, row.Make, row.Gasoline)
TypeError: function takes at most 2 arguments (4 given)
[2021-11-21 22:00:17,342] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-21 22:00:17,365] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
