[2021-11-21 21:27:36,338] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: DWBI_HW2_dag.transform manual__2021-11-21T20:27:25.507841+00:00 [queued]>
[2021-11-21 21:27:36,346] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: DWBI_HW2_dag.transform manual__2021-11-21T20:27:25.507841+00:00 [queued]>
[2021-11-21 21:27:36,347] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 21:27:36,347] {taskinstance.py:1242} INFO - Starting attempt 1 of 6
[2021-11-21 21:27:36,347] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 21:27:36,357] {taskinstance.py:1262} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2021-11-21 20:27:25.507841+00:00
[2021-11-21 21:27:36,362] {standard_task_runner.py:52} INFO - Started process 35495 to run task
[2021-11-21 21:27:36,364] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'DWBI_HW2_dag', 'transform', 'manual__2021-11-21T20:27:25.507841+00:00', '--job-id', '115', '--raw', '--subdir', '/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py', '--cfg-path', '/tmp/tmpb8qozm44', '--error-file', '/tmp/tmp_qsueucu']
[2021-11-21 21:27:36,365] {standard_task_runner.py:77} INFO - Job 115: Subtask transform
[2021-11-21 21:27:36,390] {logging_mixin.py:109} INFO - Running <TaskInstance: DWBI_HW2_dag.transform manual__2021-11-21T20:27:25.507841+00:00 [running]> on host dj-XPS
[2021-11-21 21:27:36,422] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dj
AIRFLOW_CTX_DAG_ID=DWBI_HW2_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2021-11-21T20:27:25.507841+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-21T20:27:25.507841+00:00
[2021-11-21 21:27:36,431] {logging_mixin.py:109} INFO - Successfully fetched the data
[2021-11-21 21:27:36,545] {logging_mixin.py:109} INFO -    Unnamed: 0  Unnamed: 0.1     Make     Model  ManufacturingYear     Price  Horsepower EmissionCategory         VIN   origin  Gasoline
0           0             0  Porsche  Panamera               2021  200000.0       500.0                E    10923857  Germany         1
1           1             1  Porsche   Cayenne               2019  130000.0       350.0                C   305982705  Germany         1
2           3             3  Porsche     Macan               2018  110000.0       310.0                B  2938579237  Germany         1
3           4             4     Audi        Q7               2015   70000.0       240.0                C  2035920398  Germany         0
4           5             5     Audi        A6               2012   50000.0       272.0                D   239405067  Germany         0
[2021-11-21 21:27:36,546] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py", line 96, in transform
    df = df.groupby('origin').agg({'Diesel': 'count', 'Gasoline':'count','Make': 'count'})
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 979, in aggregate
    result = op.agg()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 161, in agg
    return self.agg_dict_like()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 427, in agg_dict_like
    arg = self.normalize_dictlike_arg("agg", selected_obj, arg)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 546, in normalize_dictlike_arg
    raise KeyError(f"Column(s) {cols_sorted} do not exist")
KeyError: "Column(s) ['Diesel'] do not exist"
[2021-11-21 21:27:36,555] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=DWBI_HW2_dag, task_id=transform, execution_date=20211121T202725, start_date=20211121T202736, end_date=20211121T202736
[2021-11-21 21:27:36,568] {standard_task_runner.py:88} ERROR - Failed to execute job 115 for task transform
Traceback (most recent call last):
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dante/DWBI/Apache/dags/DWBI_HW2_dag.py", line 96, in transform
    df = df.groupby('origin').agg({'Diesel': 'count', 'Gasoline':'count','Make': 'count'})
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 979, in aggregate
    result = op.agg()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 161, in agg
    return self.agg_dict_like()
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 427, in agg_dict_like
    arg = self.normalize_dictlike_arg("agg", selected_obj, arg)
  File "/home/dante/DWBI/Apache/py_env/lib/python3.8/site-packages/pandas/core/apply.py", line 546, in normalize_dictlike_arg
    raise KeyError(f"Column(s) {cols_sorted} do not exist")
KeyError: "Column(s) ['Diesel'] do not exist"
[2021-11-21 21:27:36,616] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-21 21:27:36,637] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
